name: Build LiveStream Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Java Development Kit (JDK)
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.x'
        channel: 'stable'

    - name: Install Dependencies
      run: flutter pub get

    - name: Build Android APK
      run: flutter build apk --release

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: LiveStream-App-Release
        path: build/app/outputs/flutter-apk/app-release.apk
