name: Build Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Build Android APK
      run: |
        # Nemo inda jakar android/ take ainihi
        ANDROID_DIR=$(dirname $(find . -maxdepth 3 -name "build.gradle" -not -path "*/.*" | head -n 1))
        PROJECT_DIR=$(dirname "$ANDROID_DIR")
        echo "Moving into project directory: $PROJECT_DIR"
        cd "$PROJECT_DIR"
        
        flutter pub get
        
        MAIN_PATH=$(find . -name "main.dart" -not -path "*/.*" | head -n 1)
        echo "Found main.dart at: $MAIN_PATH"
        
        flutter build apk --release -t "$MAIN_PATH"

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: LiveStream-App-Release
        path: "**/build/app/outputs/flutter-apk/app-release.apk"
